### ISSUE TITLE
Update README link to new repository

### ISSUE THREAD

**Issue by zorun** [bodea/l2tpns#3]
Could you update the README to point to the new repository? https://code.ffdn.org/l2tpns/l2tpns

It is actively maintained, supersedes the sameswireless repository, and is now the upstream for the Debian package: https://tracker.debian.org/pkg/l2tpns

**Comment by bodea** [comment]
Done:
https://github.com/bodea/l2tpns/commit/c8209f928e85ac8d289696e03b220142b059b19b

**Comment by zorun** [comment]
Thanks a lot!
